### ISSUE TITLE
echopype 0.6.0: Update the environment file and re-run notebooks 1-2

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype-examples#25]
Once echopype 0.6.0 is available on conda-forge, push an updated `environment.yml file` (pinning echopype to 0.6.0) and re-run and push the first two notebooks solely to have the echopype __version__ printout at the end reflect 0.6.0 (the OOI notebook already does).

**Comment by emiliom** [comment]
The notebooks and site are now fully updated.

I won't close this issue yet, though, only b/c I'm seeing for the first time that a table of content is added to each notebook at the top, and the notebook title is duplicated. This is new behavior, which wasn't occurring in the netlify previews or local rendering. Given that the notebooks are found within a Jupyter Book with the table of content always accessible to the right, I think that extra TOC at the top adds clutter. There's probably a configuration that can be tuned to remove these two new elements.

**Comment by leewujung** [comment]
This one seems pretty outdated. Seems like we can close this now?

**Comment by emiliom** [comment]
Right. This issue is no longer taking place. I'm closing the issue.
