### ISSUE TITLE
Add new hake region to NASC notebook

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype-examples#43]
- expand to process data from 1-2 transects
- load EVR files to get regions
- create hake only MVBS after masking
- compute NASC
- map plot
  - plot lat/lon of both transects
  - plot NASC as color dots
- echogram plot
  - 3 frequency echogram with region contour

**Comment by ctuguinay** [comment]
Maybe edit this title to "Add New Hake Survey Notebook Focused on Masking Hake and Hake NASC"

**Comment by ctuguinay** [comment]
I'll also need to put Hake EVR files in Echoregions so that I can easily read them from a notebook.

**Comment by ctuguinay** [comment]
And I'll need to modify how the EK500 colormap is placed into Matplotlib's colormap, since the `visualize` subpackage is meant to be removed. Hopefully not a big thing to fix.

**Comment by leewujung** [comment]
> And I'll need to modify how the EK500 colormap is placed into Matplotlib's colormap, since the `visualize` subpackage is meant to be removed. Hopefully not a big thing to fix.

I did the investigation when putting in the deprecation, so I just submit #1336 and asked you to review.
Right now is you do `import echopype.colormap`, then you can use `cmap="ep.ek500"` when plotting.

**Comment by leewujung** [comment]
> I'll also need to put Hake EVR files in Echoregions so that I can easily read them from a notebook.

Oh right. Maybe put 1 EVR file in this repo instead of the Echoregions one, so that it is together with the notebook. In Echoregions I feel a minimal example like what you have is nice. I guess this is the place where we could actually put it in the release assets, so that it gets bundled with the next release of `echopype-examples`. I haven't looked into the operations though, seems something we can do a hackday with, to also get the initial stuff going to migrate Echopype test files.

**Comment by ctuguinay** [comment]
Sounds good, I'll place it in this repo. I think another PR to place stuff in release assets would be good though, after this one is merged.
