### ISSUE TITLE
Revise OOI eclipse notebook

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype-examples#45]
- goal: demonstrate using another non-acoustic data source to do joint analysis with acoustic data in a single notebook without specialized functions -- this is different from many GUI packages
- changes: 
  - reduce explanatory text to remove clutter
  - remove single file section (that is already covered in docs)
  - expand on the text regarding bringing in other data types/sources

**Comment by ctuguinay** [comment]
Closed by #51
